Adjust min serviceaccounttoken expiration to 10min
aws/amazon-eks-pod-identity-webhook pull request #207
Opened 2024-01-29 14:36 UTC by gauravpriyolkar

*Issue #:* https://github.com/aws/amazon-eks-pod-identity-webhook/issues/155

*Description of changes:*
Currently, the 1hr minimum overrides token requests for shorter expiration: https://github.com/aws/amazon-eks-pod-identity-webhook/blob/master/pkg/validation.go#L17

This change aligns minimum serviceaccount token expiration to 10min to match the minimum permissible at apiserver: https://github.com/kubernetes/kubernetes/blob/eb0fcf9e216f83e200e1c04e24d0484394da6b86/pkg/apis/core/validation/validation.go#L1148

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-01-29 16:47 UTC, DanielCKennedy requested changes
`make test` is failing. Can you update `rawPodMinTokenExpiration.pod.yaml` to change the `expectedPatch` on line 11 to have `"expirationSeconds":600` instead of 3600

https://github.com/aws/amazon-eks-pod-identity-webhook/blob/master/pkg/handler/testdata/rawPodMinTokenExpiration.pod.yaml#L11

2024-01-30 21:23 UTC, DanielCKennedy approved these changes

2024-01-30 21:50 UTC, tingrui-AWS-EKS-auth commented
Test Case:
1. Test image building.
2. Update pod-identity-webhook manifest in the cluster with new image. Confirm pod-identity-webhook start workin without errors.
3. Follow the EKS Walkthrough in the README file, to create node role, service account. Set the token-expiration of pods from 3600 to 600 seconds.
4. Create node, and pods using service account. Get pod information, comfirm the token-expiration is 600s instead of 3600.
5. Exec into pods, test aws command like ``aws iam list-roles``, to check the pod working normally.

2024-01-30 21:53 UTC, prateekgogia approved these changes
LGTM!

2024-01-30 21:53 UTC, merged